### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by githubertus** [condor2/Opencart_30xx#1]
hi,
just tried to install this one on PHP 7.3
and got a bunch of
`Uninitialized string offset: 0 in system/library/template/Twig/Lexer.php on line 163`
messages, and most likely as a side effect I couldn't proceed at page 3 because of getting
`E-Mail Address does not appear to be valid!`

After reverting
`if ($this->options['whitespace_trim'] === $this->positions[2][$this->position][0]) {`
to
`if (isset($this->positions[2][$this->position][0])) {`
installation finished without problems.

**Comment by condor2** [comment]
Test with this changes
https://github.com/condor2/Opencart_3033/commit/b400080ca887f18d8e41c0db79d6d2243f130220

**Comment by githubertus** [comment]
I have applied that fix now, and moved around a little in the front and backend,
but so far I found no location to make that outer condition come true with the default theme.
So it's hard to tell whether the inner stuff would really work or not... ;)

Anyway and aside from that let me just send you a big THANK YOU for all your active bug fixing instead of just telling this doesn't work and that doesn't work.
