### ISSUE TITLE
upgrade Issues

### ISSUE THREAD

**Issue by wewetech** [condor2/Opencart_30xx#12]
We have uploaded the files to testing environment & during installation we got these issues:

https://prnt.sc/vyeeln
https://prnt.sc/vyed6t

Seeking your support

**Comment by condor2** [comment]
Upgrade from what version...?

**Comment by wewetech** [comment]
3.0.3.6 just upgrading bootstrap & jquery

**Comment by condor2** [comment]
> just upgrading bootstrap & jquery

Then download entire oc version from here...

**Comment by wewetech** [comment]
I have done that & uploaded all files into directory .... The issue mentioned earlier is what received
