### ISSUE TITLE
amazon pay admin template missing closing twig }} at end of file.

### ISSUE THREAD

**Issue by jimradford** [condor2/Opencart_30xx#17]
While experimenting with a fresh checkout I received the following error when trying to modify the settings for amazon pay in admin / modules:

Twig\Error\SyntaxError: Unclosed "variable" in "extension/module/amazon_pay.twig" at line 113. in /usr/local/apache2/storage/vendor/twig/twig/src/Lexer.php on line 301

Fix: 
Opencart_30xx/admin/view/template/extension/module/amazon_pay.twig, footer variable is missing ending }}

Regards

**Comment by condor2** [comment]
https://github.com/condor2/Opencart_30xx/commit/17e38f30959be0dc24d9a75558ca51552b6b8eb5
