### ISSUE TITLE
Upgrade from V3.3.0.6

### ISSUE THREAD

**Issue by haxcop** [condor2/Opencart_30xx#19]
Hi I'm seeing this errors when trying to use this version of OC 
PHP V7.4

`SyntaxError: Unexpected token W in JSON at position 153 OK {"success":"Patch 1000 has been applied (1 of 10)","next":"https:\/\/www.staging.localhost.local\/install\/index.php?route=upgrade\/upgrade\/next&step=2"} Warning: Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP) in /home/USER/public_html/staging.localhost.local/system/storage/modification/system/library/response.php on line 152 Fatal error: Uncaught Error: Call to undefined method Session\File::gc() in /home/USER/public_html/staging.localhost.local/system/library/session.php:105 Stack trace: #0 [internal function]: Session->gc() #1 {main} thrown in /home/USER/public_html/staging.localhost.local/system/library/session.php on line 105`

**Comment by condor2** [comment]
Delete ocmod modifications then try to run upgrade again.
Possible that error is caused by an ocmod extension
`/staging.localhost.local/system/storage/modification/system/library/response.php`

I have made an upgrade from 3.0.3.6 and I didn't saw that errors

**Comment by haxcop** [comment]
Ok Will re test it with all the mods Disabled
