### ISSUE TITLE
PayPal (Powered by Braintree) is not connected in opencart 3.3.06

### ISSUE THREAD

**Issue by Khnaz35** [condor2/Opencart_30xx#2]
Hi, 
I have fresh install of OC_3036 and try to connect Paypal (Powered by Braintree) when am clicking the button Connect with Briantree it is redirecting to Braintree page and when login it doesn't sync the data with OC instead admin got kicked out 

![image](https://user-images.githubusercontent.com/43812103/91660002-f110df00-eb05-11ea-906a-9b265ee3be5e.png)

upon edit manually keys and saving here is the error.
Error: Class 'Braintree_Configuration' not found in /home/gqvxzdmy/public_html/xyzs/OC_3306_cordon/admin/controller/extension/payment/pp_braintree.php on line 1135

**Comment by condor2** [comment]
See if work now
https://github.com/condor2/Opencart_3036/commit/7a76a12967ff02d285d3985db52bde0d0cf9d859

**Comment by condor2** [comment]
This extension worked before?

**Comment by Khnaz35** [comment]
in 3.0.3.5 i am able to save the setting but it is not supporting recurring payment.

**Comment by condor2** [comment]
You can post on forum and maybe you get help about recurring payment.

**Comment by Khnaz35** [comment]
By default does it support recurring payment ?

**Comment by condor2** [comment]
I don't know. Never used integrated payments.
All integrated payments are useless for me.

**Comment by Khnaz35** [comment]
ah, do you have any of your own recurring payment extension which does support braintree ? I have seen jonathan one though

**Comment by condor2** [comment]
No, I don't have.

**Comment by Khnaz35** [comment]
ok, Thanks for letting me know :)
