### ISSUE TITLE
Wording / Spelling Errors in htaccess

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_30xx#27]
If your opencart installation does not run on the main web folder make sure you folder it does run in ie. / becomes /shop/

Maybe should be:

If your opencart installation does not run on the main web folder make sure you change the path to the folder it does run in ie. / becomes /shop/

set max post size. uncomment this line 
needs to be
set max post size. Uncomment this line 
(capital letter after a full stop)

set max time for input to be recieved.
wrong spelling
set max time for input to be received.

**Comment by condor2** [comment]
https://github.com/condor2/Opencart_30xx/commit/0768e1539e1fbdd390a022f813407a103e46b706
