### ISSUE TITLE
Step 3 Error

### ISSUE THREAD

**Issue by SoloApoellin** [condor2/Opencart_30xx#28]
Hi

Fresh Installation PHP8.3

I get the following error in step 3:
![Untitled](https://github.com/condor2/Opencart_30xx/assets/20866439/8e531680-f528-4be2-95b5-482205ffef4d)

Exception: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '36, 'admin_mail_gdpr', 'admin/model/customer/gdpr/editStatus/after', 'mail/gd...' at line 1
Error No: 1064
(36, 'admin_mail_gdpr', 'admin/model/customer/gdpr/editStatus/after', 'mail/gdpr', 1, 0); in /home/webrools/public_html/oc/system/library/db/mysqli.php on line 48

My server Info:
cPanel Version | 110.0 (build 17)
Apache Version | 2.4.58
MySQL Version | 10.6.16-MariaDB-cll-lve-log

**Comment by condor2** [comment]
Missing insert command
https://github.com/condor2/Opencart_30xx/commit/bcb81369a7490bb4784f0913e60c4fd576dec480#diff-880ba7a3ba2dd91438579ab05abbefd08aa82145b614017a47bef72f15db1d82
