### ISSUE TITLE
Theme installation

### ISSUE THREAD

**Issue by SoloApoellin** [condor2/Opencart_30xx#29]
Hi

Trying to install iStore Theme, that only applies css changes to the default theme.
Although in extensions/themes it shows that there are 2 themes available, only default theme is visible.

![Untitled](https://github.com/condor2/Opencart_30xx/assets/20866439/11642980-a2d6-4b49-9250-b2815c646a35)

Thanks

**Comment by condor2** [comment]
I don;t know how Istore is made

**Comment by SoloApoellin** [comment]
[Theme-oc3.zip](https://github.com/condor2/Opencart_30xx/files/13866938/Theme-oc3.zip)

**Comment by condor2** [comment]
Switch to the Theme in Settings

**Comment by SoloApoellin** [comment]
But shouldn't i activate the extra theme from Extensions/Themes first?

**Comment by condor2** [comment]
Yes.
Try to select all user group permissions.

**Comment by SoloApoellin** [comment]
Ok. Thanks a lot
