### ISSUE TITLE
Paypal Standard

### ISSUE THREAD

**Issue by SoloApoellin** [condor2/Opencart_30xx#3]
Hi

It seems i cannot find Paypal Standard. Is it not installed?

![paypal](https://user-images.githubusercontent.com/20866439/91770465-e3348a00-ebe9-11ea-8a14-149f24f7c4ad.jpg)

**Comment by condor2** [comment]
All extension should be there. Reupload again all files and try to clear browser cache.

**Comment by SoloApoellin** [comment]
I did clear all the caches with no result. Even in browser incognito mode only Paypal powered by braintree appeared. 
But after reupload and clear all browser cache again all paypal extensions appeared. The reupload fix the problem. Thanks

**Comment by condor2** [comment]
Somehow when you install broke....user permissions...

I will check

**Comment by SoloApoellin** [comment]
Yes i forgot to mention that.  After i reupload, i run a check all in user permission just to be sure. Maybe was that the problem

**Comment by SoloApoellin** [comment]
Hi again. it seems in every installation of a module or a theme, either clear cache or not,  you must go to User Groups and uncheck - check all permissions again in order to find the module or the theme
