### ISSUE TITLE
datepicker is not working.

### ISSUE THREAD

**Issue by Dev-2021** [condor2/Opencart_30xx#8]
Datepicker not working with jquery3.5.1

**Comment by condor2** [comment]
More details...

Screenshot, where not working...

**Comment by Dev-2021** [comment]
On the returns page(not tested on other pages), nothing when clicking on the button but its works when if switch back to jquery-2.2.4
Here are screenshots
https://gyazo.com/a8c3b9909ef8771cc836b937ed19a19e
https://gyazo.com/d38e01242959360a5ebee3e50783d767

**Comment by condor2** [comment]
You use Default theme?
You have the latest version from here?

Work just fine for me

**Comment by Dev-2021** [comment]
I created a theme, 

it doesn't work with jquery 3.5.1 on the default theme or custom theme but works fine with older versions of jquery.
